/* 
 * Demo Platform
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace dhango.Web.Sdk
{
    /// <summary>
    /// Defines BankAccountType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum BankAccountType
    {
        /// <summary>
        /// Enum PersonalSavings for value: PersonalSavings
        /// </summary>
        [EnumMember(Value = "PersonalSavings")]
        PersonalSavings = 1,
        /// <summary>
        /// Enum PersonalChecking for value: PersonalChecking
        /// </summary>
        [EnumMember(Value = "PersonalChecking")]
        PersonalChecking = 2,
        /// <summary>
        /// Enum CorporateSavings for value: CorporateSavings
        /// </summary>
        [EnumMember(Value = "CorporateSavings")]
        CorporateSavings = 3,
        /// <summary>
        /// Enum CorporateChecking for value: CorporateChecking
        /// </summary>
        [EnumMember(Value = "CorporateChecking")]
        CorporateChecking = 4    }
}
