/* 
 * Demo Platform
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = dhango.Web.Sdk.Client.SwaggerDateConverter;

namespace dhango.Web.Sdk.Model
{
    /// <summary>
    /// Defines CardBrand
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum CardBrand
    {
        /// <summary>
        /// Enum Visa for value: Visa
        /// </summary>
        [EnumMember(Value = "Visa")]
        Visa = 1,
        /// <summary>
        /// Enum Mastercard for value: Mastercard
        /// </summary>
        [EnumMember(Value = "Mastercard")]
        Mastercard = 2,
        /// <summary>
        /// Enum AmericanExpress for value: AmericanExpress
        /// </summary>
        [EnumMember(Value = "AmericanExpress")]
        AmericanExpress = 3,
        /// <summary>
        /// Enum Discover for value: Discover
        /// </summary>
        [EnumMember(Value = "Discover")]
        Discover = 4    }
}
