/* 
 * Demo Platform
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = dhango.Web.Sdk.Client.SwaggerDateConverter;

namespace dhango.Web.Sdk.Model
{
    /// <summary>
    /// Defines PaymentMethodType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PaymentMethodType
    {
        /// <summary>
        /// Enum Card for value: Card
        /// </summary>
        [EnumMember(Value = "Card")]
        Card = 1,
        /// <summary>
        /// Enum ACH for value: ACH
        /// </summary>
        [EnumMember(Value = "ACH")]
        ACH = 2
    }
}
