/* 
 * Demo Platform
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = dhango.Web.Sdk.Client.SwaggerDateConverter;

namespace dhango.Web.Sdk.Model
{
    /// <summary>
    /// Defines TransactionEventType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransactionEventType
    {
        /// <summary>
        /// Enum Payment for value: Payment
        /// </summary>
        [EnumMember(Value = "Payment")]
        Payment = 1,
        /// <summary>
        /// Enum Authorization for value: Authorization
        /// </summary>
        [EnumMember(Value = "Authorization")]
        Authorization = 2,
        /// <summary>
        /// Enum Capture for value: Capture
        /// </summary>
        [EnumMember(Value = "Capture")]
        Capture = 3,
        /// <summary>
        /// Enum Refund for value: Refund
        /// </summary>
        [EnumMember(Value = "Refund")]
        Refund = 4,
        /// <summary>
        /// Enum Return for value: Return
        /// </summary>
        [EnumMember(Value = "Return")]
        Return = 5,
        /// <summary>
        /// Enum Chargeback for value: Chargeback
        /// </summary>
        [EnumMember(Value = "Chargeback")]
        Chargeback = 6,
        /// <summary>
        /// Enum ChargebackReversal for value: ChargebackReversal
        /// </summary>
        [EnumMember(Value = "ChargebackReversal")]
        ChargebackReversal = 7,
        /// <summary>
        /// Enum ChargebackDispute for value: ChargebackDispute
        /// </summary>
        [EnumMember(Value = "ChargebackDispute")]
        ChargebackDispute = 8,
        /// <summary>
        /// Enum Settle for value: Settle
        /// </summary>
        [EnumMember(Value = "Settle")]
        Settle = 9,
        /// <summary>
        /// Enum Process for value: Process
        /// </summary>
        [EnumMember(Value = "Process")]
        Process = 10,
        /// <summary>
        /// Enum Reject for value: Reject
        /// </summary>
        [EnumMember(Value = "Reject")]
        Reject = 11,
        /// <summary>
        /// Enum Void for value: Void
        /// </summary>
        [EnumMember(Value = "Void")]
        Void = 12    }
}
